export const testValue = {
  id: "147226984697",
  productTitle: "КС-Г(В)-010 СН",
  updatedAt: "2024-123",
  norms: {
    main_group: {
      type: "main",
      title: "КС-Г(В)-010 СН",
      code: "070.00.00.000",
      modification: "010CH",
      detail_order: ["detail_nCkXu8"],
      details: {
        detail_nCkXu8: {
          type: "detail",
          title: "adasd",
          assortment: "asdasd",
          standard: "dfsdf",
          unit: "sada",
          consuption_rate: "",
          consuption_rate_per_item: "",
          price: "",
          sum: "",
          notes: "",
        },
      },
    },
    group_nCkXU7: {
      type: "group",
      title: "Панель передня",
      code: "",
      unit: "",
      quantity: "",
      detail_order: ["detail_nCkXN4"],
      details: {
        detail_nCkXN4: {
          type: "detail",
          title: "adasd",
          assortment: "asdasd",
          standard: "dfsdf",
          unit: "sada",
          consuption_rate: "",
          consuption_rate_per_item: "",
          price: "",
          sum: "",
          notes: "",
        },
      },
    },
    spacing_aUsn7: {
      type: "spacing",
      id: "id",
    },
    heading_asYwb: {
      id: "id",
      type: "heading",
      value: "Another details",
    },
    detail_nCkXu8: {
      type: "detail",
      title: "adasd",
      assortment: "asdasd",
      standard: "dfsdf",
      unit: "sada",
      consuption_rate: "",
      consuption_rate_per_item: "",
      price: "",
      sum: "",
      notes: "",
    },
    order: [
      "main_group",
      "group_nCkXU7",
      "spacing_aUsn7",
      "heading_asYwb",
      "detail_nCkXu8",
    ],
  },
};
