export const testNorms = [
  {
    order: "0",
    id: "nCkXoKP",
    type: "group",
    title: "КС-Г(В)-010 СН",
    code: "070.00.00.000",
    details: [
      {
        order: "0",
        id: "nCkXu8",
        type: "detail",
        title: "Болт з шестигранною головкою",
        assortment: "M 8x3558019",
        standard: "7798-70",
        unit: "кг",
        consuption_rate: "0.000011",
        consuption_rate_per_item: "0.000012",
        price: "",
        sum: "",
        notes: "",
      },
      {
        order: "1",
        id: "nCkXu9",
        type: "detail",
        title: "Гайка шестигранна класу точності",
        assortment: "M 4.5.0.19",
        standard: "5915-70",
        unit: "кг",
        consuption_rate: "0.0008",
        consuption_rate_per_item: "0.0008",
        price: "",
        sum: "",
        notes: "",
      },
    ],
  },
  {
    order: "1",
    id: "nCkXU7",
    type: "group",
    title: "Панель передня",
    code: "",
    unit: "",
    quantity: "",
    details: [
      {
        order: "0",
        id: "nCkXN4",
        type: "detail",
        title: "Вічко 220 v-4,8",
        assortment: "",
        standard: "",
        unit: "шт",
        consuption_rate: "2",
        consuption_rate_per_item: "2",
        price: "",
        sum: "",
        notes: "",
      },
    ],
  },
];
